proyectoTesis/urls.py
from django.contrib import admin
from django.urls import path, include
from appAgua.views import *
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login_view, name='vista_login'),
    path('login/', login_view, name='vista_login'),
    path('inicio/', inicio_view, name='vista_inicio'),
    path('logout/', logout_view, name='vista_logout'),

    path('crearUsuario/', registrarUsuario_view, name='crearUsuario'),
    path('listar_usuario/',login_required(ListadoUsuarios.as_view()), name='listar_usuario'),
    path('modificarUsuario/<int:idUsuario>/', actualizarUsuario_view, name='modificarUsuario'),
    
    path('crearTesorero/', crearTesorero_view, name='vista_crearTesorero'),
    path('listarTesoreros/',login_required(ListadoTesoreros.as_view()), name='listarTesoreros'),
    path('editarTesorero/<int:id>/',actualizarTesorero_view, name='vista_editarTesorero'),
    
    path('listarServicios/',login_required(ListadoServicios.as_view()), name='vista_listarServicios'),
    path('nuevoServicio/',nuevoServicioAgua_view, name='vista_nuevoServicioAgua'),
    path('activarServicio/<int:pk>/',login_required(ActivarServicio.as_view()), name='vista_activarServicio'),
    path('suspenderServicio/<int:id>/',SuspenderServicio, name='suspenderServicio'),

    path('listarPagos/',login_required(ListadoPagos.as_view()), name='listarPagos'),
    path('crearPago/',crearPago_view, name='vista_crearPago'),

    path('consultar/<int:pk>/',login_required(ConsultaPagos.as_view()), name='vista_consultarInformacion'),
    path('recibo/<int:pk>/', login_required(ReciboPdf.as_view()), name="recibo"),

    path('historial/',login_required(Historial.as_view()),name='historial'),
]

admin.site.site_header = 'SISTEMA DE PAGOS DE AGUA'

appAgua/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.safestring import mark_safe

class Persona(models.Model):
    nombres = models.CharField(max_length=250)
    apellidos = models.CharField(max_length=250)
    cedula = models.CharField(max_length=10)
    celular = models.CharField(max_length=10)
    correo = models.EmailField()

class Tesorero(Persona):
    idTesorero = models.AutoField(primary_key=True)
    estado = models.BooleanField('Estado', default=True)

    def __str__(self):
        return (self.nombres+' '+self.apellidos)

    class Meta:
        verbose_name = 'Tesorero'
        verbose_name_plural = 'Tesoreros'

class Usuario(Persona):
    idUsuario = models.AutoField(primary_key=True)
    usuarioAgua = models.OneToOneField(User, on_delete=models.CASCADE, default="")

    def __str__(self):
        return (self.nombres+' '+self.apellidos)

    class Meta:
        verbose_name = 'Usuario'
        verbose_name_plural = 'Usuarios'

class Pago(models.Model):
    idPago = models.AutoField(primary_key=True)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    tesorero = models.ForeignKey(Tesorero, on_delete=models.CASCADE)
    mesDesde = models.DateField()
    mesHasta = models.DateField()
    costoServicio = models.DecimalField(decimal_places=2, max_digits=4)

    def __str__(self):
        return self.usuario.nombres

    class Meta:
        verbose_name = 'Pago de Agua'
        verbose_name_plural = 'Pagos de Agua'

class ServicioAgua(models.Model):
    idServicioAgua = models.AutoField(primary_key=True)
    usuario = models.OneToOneField(Usuario, on_delete=models.CASCADE)
    costoActivacion = models.DecimalField(decimal_places=2, max_digits=4)
    motivoSuspension = models.TextField()
    estado = models.BooleanField('Estado', default=True)

    def __str__(self):
        return self.usuario.nombres

    class Meta:
        verbose_name = 'Servicio de Agua'
        verbose_name_plural = 'Servicios de Agua'

class HistorialServicio(models.Model):
    idHistorial = models.AutoField(primary_key=True)
    usuario = models.CharField(max_length=250)
    costoActivacion = models.DecimalField(decimal_places=2, max_digits=4)
    motivoSuspension = models.TextField()
    fechaSuspension = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.usuario

    class Meta:
        verbose_name = 'Historial de Servicio'
        verbose_name_plural = 'Historial de Servicios'

appAgua/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput(render_value=False))

    class Meta:
        model = User
        fields = ['username','password']

class UsuarioForm(UserCreationForm):
    nombres = forms.CharField(widget=forms.TextInput())
    apellidos = forms.CharField(widget=forms.TextInput())
    cedula = forms.CharField(widget= forms.TextInput())
    celular = forms.CharField(widget= forms.TextInput())
    correo = forms.EmailField(widget= forms.EmailInput())

class PagoForm(forms.ModelForm):
    
    class Meta:
        model = Pago
        fields = ['usuario','tesorero','mesDesde','mesHasta','costoServicio']
        
    def __init__(self, *args, **kwargs):  
        super().__init__(*args, **kwargs)  
        for field in iter(self.fields):  
            self.fields[field].widget.attrs.update({
                'class': 'form-control'  
            })
        self.fields['mesDesde'].widget.attrs['readonly'] = True
        self.fields['mesHasta'].widget.attrs['readonly'] = True

class UsuarioForms(forms.ModelForm):

    class Meta:
        model = Usuario
        fields = ['nombres','apellidos','cedula','celular','correo']
        labels = {
            'nombres': 'Nombres:',
            'apellidos': 'Apellidos:',
            'cedula': 'N° Cedula:',
            'celular': 'Celular:',
            'correo': 'Correo:',
        }

    def __init__(self, *args, **kwargs):  
        super().__init__(*args, **kwargs)  
        for field in iter(self.fields):  
            self.fields[field].widget.attrs.update({  
            'class': 'form-control'  
            })     

class TesoreroForm(forms.ModelForm):

    class Meta:
        model = Tesorero
        fields = ['nombres','apellidos','cedula','celular','correo']
        labels = {
            'nombres': 'Nombres:',
            'apellidos': 'Apellidos:',
            'cedula': 'N° Cedula:',
            'celular': 'Celular:',
            'correo': 'Correo:',
        }

    def __init__(self, *args, **kwargs):  
        super().__init__(*args, **kwargs)  
        for field in iter(self.fields):  
            self.fields[field].widget.attrs.update({  
            'class': 'form-control'  
            })     

class ServicioForm(forms.ModelForm):
    class Meta:
        model = ServicioAgua
        fields = ['usuario','costoActivacion','motivoSuspension']
        labels = {
            'usuario': 'Usuario',
            'costoActivacion': 'Costo de Activación',
            'motivoSuspension': 'Motivo de Suspensión',
        }

    def __init__(self, *args, **kwargs):  
        super().__init__(*args, **kwargs)  
        for field in iter(self.fields):  
            self.fields[field].widget.attrs.update({  
            'class': 'form-control'  
            })  
            
class HistorialForm(forms.ModelForm):
    class Meta:
        model = HistorialServicio
        fields = ['usuario','costoActivacion','motivoSuspension']
    

appAgua/views.py
from django.shortcuts import render, redirect
from io import BytesIO
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import View, TemplateView, ListView, UpdateView, CreateView, DeleteView
from django.urls import reverse_lazy
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from .forms import *
import json
from django.db.models import Count, Q
#import matplotlib.pyplot as plt
from xhtml2pdf import pisa
from django.template.loader import get_template

class MixinFormInvalid:
    def form_invalid(self, form):
            response = super().form_invalid(form)
            if self.request.is_ajax():
                return JsonResponse(form.errors, status=400)
            else:
                return response

def login_view(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('/inicio/')
    else:
        if request.method == 'POST':
            form = LoginForm(request.POST)
            if form.is_valid():
                username = form.cleaned_data['username']
                password = form.cleaned_data['password']
                usuario = authenticate(username=username,password=password)
                if usuario is not None and usuario.is_active:
                    login(request,usuario)
                    messages.success(request,"Bienvenido al Sistema de Pagos de Agua")
                    return HttpResponseRedirect('/inicio/')
        form = LoginForm()
        ctx = {'form':form}
        return render(request,'login.html',ctx)

def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/login/')

@login_required(login_url='/login/')
def inicio_view(request):
    usuario = Usuario.objects.all()
    ctx = {'usuario': usuario}
    return render(request,'vista_principal.html', ctx)

################     USUARIO     #################

class ListadoUsuarios(ListView):
    model = Usuario
    template_name = 'usuario/listar_usuarios.html'
    queryset = Usuario.objects.order_by('idUsuario')
    context_object_name = 'usuarios'

def cedula_rep(nro, lista):
    #tesoreros = Tesorero.objects.all()
    numero_ced = nro
    rep = 0
    for l in lista:
        if l.cedula == numero_ced:
            rep = rep + 1
    # for t in tesoreros:
    #     if t.cedula == numero_ced:
    #         rep = rep + 1
    return rep

def user_rep(user, lista):
    user = user
    rep = 0
    for l in lista:
        if l.username == user:
            rep+= 1
    return rep 

def validarCedula(nro):
    l = len(nro)
    if l == 10 or l == 13: # verificar la longitud correcta
        cp = int(nro[0:2])
        if cp >= 1 and cp <= 22: # verificar codigo de provincia
            tercer_dig = int(nro[2])
            if tercer_dig >= 0 and tercer_dig < 6 : # numeros enter 0 y 6
                if l == 10:                   
                    return __validar_ced_ruc(nro,0)                       
                elif l == 13:
                    return __validar_ced_ruc(nro,0) and nro[10:13] != '000' # se verifica q los ultimos numeros no sean 000
            elif tercer_dig == 6:
                return __validar_ced_ruc(nro,1) # sociedades publicas
            elif tercer_dig == 9: # si es ruc
                return __validar_ced_ruc(nro,2) # sociedades privadas
            else:
                return 'Tercer digito invalido'
        else:
            return 'Codigo de provincia incorrecto'
    else:
        return 'Longitud incorrecta del numero ingresado'

def __validar_ced_ruc(nro,tipo):
    total = 0
    if tipo == 0: # cedula y r.u.c persona natural
        base = 10
        d_ver = int(nro[9])# digito verificador
        multip = (2, 1, 2, 1, 2, 1, 2, 1, 2)
    elif tipo == 1: # r.u.c. publicos
        return 'La cedula debe contener 10 digitos'
    elif tipo == 2: # r.u.c. juridicos y extranjeros sin cedula
        return 'La cedula debe contener 10 digitos'
    for i in range(0,len(multip)):
        p = int(nro[i]) * multip[i]
        if tipo == 0:
            total+=p if p < 10 else int(str(p)[0])+int(str(p)[1])
        else:
            total+=p
    mod = total % base
    val = base - mod if mod != 0 else 0
    return val == d_ver

def validarNumero(nro):
    l = len(nro)
    if l == 10:
        return True
    else:
        return False

@login_required
def registrarUsuario_view(request):
    usuarios = Usuario.objects.all()
    users = User.objects.all()
    if request.method == "POST":
        form = UsuarioForm(request.POST)
        cedula = cedula_rep(request.POST.get("cedula",""), usuarios)
        usuario = user_rep(request.POST.get("username"), users)
        cedulaV = validarCedula(request.POST.get("cedula",""))
        celularV = validarNumero(request.POST.get("celular",""))
        if form.is_valid():
            if cedulaV == True:
                if celularV == True:
                    if cedula == 0:
                        if usuario == 0:    
                            user = form.save()
                            usuario = Usuario()
                            usuario.usuarioAgua = user
                            usuario.nombres = form.cleaned_data['nombres']
                            usuario.apellidos = form.cleaned_data['apellidos']
                            usuario.cedula = form.cleaned_data['cedula']
                            usuario.celular = form.cleaned_data['celular']
                            usuario.correo = form.cleaned_data['correo']
                            usuario.save()
                            messages.success(request, "Usuario Registrado con Éxito!")
                            return redirect(to='listar_usuario')
                        else:
                            return render(request,'usuario/registrar_usuario.html',{'error':'Usuario ya Existe','form':form})
                    else:
                        return render(request,'usuario/registrar_usuario.html',{'error':'Cedula ya Existe','form':form})
                else:
                        return render(request,'usuario/registrar_usuario.html',{'error':'Celular debe tener 10 dígitos','form':form})
            else:
                return render(request, 'usuario/registrar_usuario.html',{'error':'Cedula Inválida','form':form})
        else:
            return render(request,'usuario/registrar_usuario.html',{'form':form})
    else:
        return render(request,'usuario/registrar_usuario.html')

@login_required
def actualizarUsuario_view(request, idUsuario):
    usuario = Usuario.objects.get(idUsuario=idUsuario)
    usuarios = Usuario.objects.all()
    if request.method == "POST":
        form = UsuarioForms(request.POST, instance=usuario) 
        if form.is_valid():
            form.save()
            messages.success(request,"Usuario modificado con Éxito!")
            return redirect(to='listar_usuario')
        else:
            form = UsuarioForms(instance=usuario)
    else:
        form = UsuarioForms(instance=usuario)
        return render(request, 'usuario/modificar_usuario.html',{"u":usuario,'form':form})

################     TESOREROS         ###############

class ListadoTesoreros(ListView):
    model = Tesorero
    template_name = 'tesorero/listar_tesoreros.html'
    queryset = Tesorero.objects.order_by('idTesorero')
    context_object_name = 'tesoreros'

@login_required
def crearTesorero_view(request):
    tesoreros = Tesorero.objects.all()
    if request.method == 'POST':
        form = TesoreroForm(request.POST)
        cedula = cedula_rep(request.POST.get("cedula",""), tesoreros)
        cedulaV = validarCedula(request.POST.get("cedula",""))
        celularV = validarNumero(request.POST.get("celular",""))
        if form.is_valid():
            if cedulaV == True:
                if celularV == True:
                    if cedula == 0:
                        tesorero = Tesorero()
                        tesorero.nombres = form.cleaned_data['nombres']
                        tesorero.apellidos = form.cleaned_data['apellidos']
                        tesorero.cedula = form.cleaned_data['cedula']
                        tesorero.celular = form.cleaned_data['celular']
                        tesorero.correo = form.cleaned_data['correo']
                        tesorero.save()
                        messages.success(request, "Tesorero Registrado con Éxito!")
                        return redirect(to='listarTesoreros')
                    else:
                        return render(request,"tesorero/nuevo_tesorero.html", {'error':'Tesorero ya Existe!','form':form})
                else:
                    return render(request, "tesorero/nuevo_tesorero.html",{'error':'Celular debe tener 10 dígitos','form':form})
            else:
                return render(request, "tesorero/nuevo_tesorero.html", {'error':'Cedula Inválida','form':form})
        else:
            return render(request, "tesorero/nuevo_tesorero.html",{'form':form})
    else:
        return render(request,'tesorero/nuevo_tesorero.html')

@login_required
def actualizarTesorero_view(request,id):
    t = Tesorero.objects.get(idTesorero=id)
    tesoreros = Tesorero.objects.all()
    if request.method == 'POST':
        form = TesoreroForm(request.POST, instance=t)
        cedula = request.POST.get("cedula","")
        lonCelular = request.POST.get("celular","")
        if len(lonCelular) == 10:
            if form.is_valid():
                form.save()
                messages.success(request, "Tesorero Actualizado con Éxito!")
                return redirect(to='listarTesoreros')
            else:
                form = TesoreroForm(instance=t)
        else:

appAgua/templates/servicios/activar_servicio.html
{% extends '../vista_principal.html' %}
{% block titulo %}
Activar Servicio
{% endblock titulo %}

{% block body %}
<form method="POST">
    {% csrf_token %}
    <div>
        <p><strong>Desea activar el servicio para:</strong></p>
        <h3 class="m-3">{{ object.usuario.nombres }} {{object.usuario.apellidos }}</h3>
        <button class="btn btn-primary" type="submit"><i class="fa fa-check-square-o"></i> Activar Servicio</button>
        <a class="btn btn-danger" href="{% url 'vista_listarServicios' %}"><i class="fa fa-times-circle"></i> Cancelar</a>
    </div>
</form>

{% endblock body %}

appAgua/templates/servicios/historial.html
{% extends '../vista_principal.html' %}
{% block titulo %}
Historial de Servicios
{% endblock titulo %}

{% block body %}

<div style="margin-bottom: 10px;">
    <a class="btn btn-success" type="button" href="/listarServicios/"><i class="fa fa-file-text-o"></i> Servicios Agua</a>
</div>

{% if serviciosHistorial %}
    <div class="card-header text-center bg-secondary text-white">
        <i class="fa fa-file-text-o"></i> <strong>Historial de Servicios de Agua</strong>
    </div>
    <br>
    <div class="table-stats order-table ov-h bg-light">
        <table class="table display" id="table_id">
            <thead>
                <tr>
                    <th>Usuario</th>
                    <th>Costo Activacion</th>
                    <th>Motivo Suspensión</th>
                    <th>Fecha Suspensión</th>
                </tr>
            </thead>
            <tbody>
                {% for s in serviciosHistorial %}
                <tr class="bg-light">
                    <td>{{s.usuario}}</td> 
                    <td>{{s.costoActivacion}}</td>
                    <td>{{s.motivoSuspension}}</td>
                    <td>{{s.fechaSuspension}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% else %}
    <h4 class="p-2 text-sm-center">No existen Suspensiones de Servicios de Agua registrados.</h4>
{% endif %}

{% endblock body %}

{% block extrajs %}

<script type="text/javascript">
    var $ = jQuery.noConflict();
    $(document).ready( function () {
        $('#table_id').DataTable({
            "aLengthMenu": [[5, 10, 15, -1], [5, 10, 15, "All"]],
            "language": {
                "url": "//cdn.databases.net/plug-ins/9dcbecd42ad/i18n/Spanish.json",
                "lengthMenu": "Mostrar _MENU_ ",
                "zeroRecords": "Registro no encontrado",
                "info": "Mostrando _END_ de _TOTAL_ registros.",
                "infoEmpty": "No hay registros disponibles",
                "infoFiltered": "(filtered from _MAX_ registros totales)",
                "pagingType": "full_numbers",
                "search": "Buscar: ",
                "responsive": true,
            }
        });
    } );
</script>

{% endblock extrajs %}

appAgua/templates/servicios/listar_servicios.html
{% extends '../vista_principal.html' %}
{% block titulo %}
Servicios de Agua
{% endblock titulo %}

{% block body %}

<div style="margin-bottom: 10px;">
    <a class="btn btn-primary" type="button" href="{% url 'vista_nuevoServicioAgua' %}">
        <i class="fa fa-plus"></i> Nuevo Servicio Agua
    </a>
    <a class="btn btn-success" type="button" href="/historial/">
        <i class="fa fa-file-text-o"></i> Historial
    </a>
</div>

{% if servicios %}
    <div class="card-header text-center bg-secondary text-white text-uppercase">
        <i class="fa fa-file-text-o"></i> <strong>Listado Servicios de Agua</strong>
    </div>
    <br>
    <div class="table-stats order-table ov-h bg-light">
        <table class="table display" id="table_id">
            <thead>
                <tr>
                    <th>Usuario</th>
                    <th>Costo Activacion</th>
                    <th>Motivo Suspensión</th>
                    <th>Opciones</th>
                </tr>
            </thead>
            <tbody>
                {% for s in servicios %}
                <tr class="bg-light">
                    <td>{{s.usuario.nombres}} {{s.usuario.apellidos}}</td> 
                    <td>{{s.costoActivacion}}</td>
                    <td>{{s.motivoSuspension}}</td>
                    <td>
                        {% if s.estado %}
                            <a class="btn btn-danger text-light" href="{% url 'suspenderServicio' s.idServicioAgua %}">
                                <i class="fa fa-thumbs-o-down"></i> Suspender Servicio
                            </a>
                        {% else %}
                            <a class="btn btn-primary" href="{% url 'vista_activarServicio' s.idServicioAgua %}">
                                <i class="fa fa-check-square-o"></i> Activar Servicio
                            </a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% else %}
    <h4 class="p-2 text-sm-center">No existen Servicios de Agua registrados.</h4>
{% endif %}

{% endblock body %}

{% block extrajs %}

<script type="text/javascript">
    var $ = jQuery.noConflict();
    $(document).ready( function () {
        $('#table_id').DataTable({
            "aLengthMenu": [[5, 10, 15, -1], [5, 10, 15, "All"]],
            "language": {
                "url": "//cdn.databases.net/plug-ins/9dcbecd42ad/i18n/Spanish.json",
                "lengthMenu": "Mostrar _MENU_ ",
                "zeroRecords": "Registro no encontrado",
                "info": "Mostrando _END_ de _TOTAL_ registros.",
                "infoEmpty": "No hay registros disponibles",
                "infoFiltered": "(filtered from _MAX_ registros totales)",
                "pagingType": "full_numbers",
                "search": "Buscar: ",
                "responsive": true,
            }
        });
    } );
</script>

{% endblock extrajs %}

appAgua/templates/servicios/nuevo_servicioAgua.html
{% extends '../vista_principal.html' %}
{% block titulo %} Registrar Servicio Agua {% endblock %}

{% block body %}

<div class="row">
    <div class="col-2"></div>
    <div class="col-8">
        <div class="text-center bg-facebook text-white p-2">
            <h4><i class="fa fa-plus"></i> NUEVO SERVICIO AGUA</h4>
        </div>
        <div class="bg-light p-3">
            <form method="POST" enctype="multipart/form-data" novalidate>
                {% csrf_token %}
                {% if form.errors %}
                <div class="alert alert-danger alert-dismissible" role="alert" id="liveAlert">
                    <strong>Faltan datos: </strong> 
                    {% for error in form.errors %}
                        {{ error }} -
                    {% endfor %}
                </div>
                {% endif %}
                <p class="text-dark">Campos Obligatorios <span class="text-danger">*</span></p>
                <div class="mb-3">
                    <div class="fieldWrapper col-sm12 control-label mb-2">
                        <div>Usuario <span class="text-danger">*</span>:</div>
                        <div class="row-nombre">
                            <select class="form-control" id="usuario" name="usuario">
                                <option selected>--- Seleccione un usuario ---</option>
                                {% for usuario in usuarios  %}
                                <option value="{{usuario.pk}}">{{usuario.nombres}} {{usuario.apellidos}}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="fieldWrapper col-sm12 control-label mb-2">
                        <div>Costo Activación <span class="text-danger">*</span>:</div>
                        <div class="row-nombre">
                            <input type="number" name="costoActivacion" id="costoActivacion" required="True" class="form-control" value="{{form.costoActivacion.value}}" placeholder="Ingrese el costo de activación">
                        </div>
                    </div>
                    <div class="fieldWrapper col-sm12 control-label mb-2">
                        <div>Motivo Suspensión <span class="text-danger">*</span>:</div>
                        <div class="row-nombre">
                            <input type="text" name="motivoSuspension" id="motivoSuspension" required="True" class="form-control" value="{{form.motivoSuspension.value}}" placeholder="Ingrese el motivo de suspensión">
                        </div>
                    </div>
                    <br>
                    <center>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary mr-2 w-25"><i class="fa fa-floppy-o"></i> Registrar</button>
                            <a class="btn btn-danger w-25" href="/listarServicios/"><i class="fa fa-times-circle"></i> Cancelar</a>
                        </div>
                    </center>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts_local %}  
 <script>  
  $(function () {  
   $("#id_mesDesde").datetimepicker({  
       format: 'd/m/Y',  
       timepicker:false  
   });  
   $("#id_mesHasta").datetimepicker({  
       format: 'd/m/Y',  
       timepicker:false  
   });  
  });  
 </script> 
 
 <script>  
    $(document).ready(function () {  
          jQuery.datetimepicker.setLocale('es');  
    });  
  </script> 
 {% endblock scripts_local %}

<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
{% if error %}
    <script>
        Swal.fire({
        "icon": "error",
        "text": "{{error}}"
    })
    </script>
{% endif %}

appAgua/templates/servicios/suspender_servicio.html
{% extends '../vista_principal.html' %}
{% block titulo %} Suspender Servicio {% endblock %}

{% block body %}

<div class="row">
    <div class="col-2"></div>
    <div class="col-8">
        <div class="text-white bg-facebook text-center p-2">
            <h4><i class="fa fa-thumbs-o-down"></i> SUSPENDER SERVICIO</h4>
        </div>
        <div class="bg-light p-3">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mt-2 mb-3">
                    <p class="text-dark">Campos Obligatorios <span class="text-danger">*</span></p>
                    {% for field in form %}
                        {{ field.label }} <span class="text-danger">*</span>:
                        {{ field }}
                        <div class="m-2"></div>
                    {% endfor %}
                </div>
                <br>
                <center><div class="form-group">
                    <button type="submit" class="btn btn-primary mr-2 w-25"><i class="fa fa-thumbs-o-down"></i> Suspender</button>
                    <a class="btn btn-danger w-25" href="/listarServicios/"><i class="fa fa-times-circle"></i> Cancelar</a>
                </div></center>
            </form>
        </div>
    </div>
</div>
{% endblock %} 